
img1:
  img_path : /src/nida_art/Oil_Painting/painting.jpeg
  caption : TBD caption
  
img2:
  img_path : /src/nida_art/Oil_Painting/painting_2.jpeg
  caption : TBD caption
  
img3:
  img_path : /src/nida_art/Oil_Painting/painting_4.jpeg
  caption : TBD caption
  
img4:
  img_path : /src/nida_art/Oil_Painting/burning_girl.jpeg 
  caption : TBD caption
  
img5:
  img_path : /src/nida_art/Oil_Painting/op_ear.jpg 
  caption : TBD caption
  
img6:
  img_path : /src/nida_art/Oil_Painting/animal.jpeg 
  caption : TBD caption
  
img7:
  img_path : /src/nida_art/Oil_Painting/bottle.jpeg 
  caption : TBD caption
  
img8:
  img_path : /src/nida_art/Oil_Painting/winter.jpeg 
  caption : TBD caption