
img7:
  img_path : /src/nida_art/Charcoal/drawing_7.jpeg
  caption : TBD caption
  
img8:
  img_path : /src/nida_art/Charcoal/drawing_8.jpeg
  caption : TBD caption
    
img9:
  img_path : /src/nida_art/Charcoal/drawing_9.jpeg
  caption : TBD caption
  
img10:
  img_path : /src/nida_art/Charcoal/drawing_10.jpeg
  caption : TBD caption
  
img1:
  img_path : /src/nida_art/Charcoal/drawing_1.jpeg
  caption : TBD caption
  
img3:
  img_path : /src/nida_art/Charcoal/drawing_3.jpeg
  caption : TBD caption

img4:
  img_path : /src/nida_art/Charcoal/drawing_4.jpeg
  caption : TBD caption