
img1:
  img_path : /src/lt.jpg
  caption : Lake Tahoe, United States. DJI, FC3411. Zongnan Bao
  
img2:
  img_path : /src/Latvia.jpg
  caption : Arkādijas parks, Riga, Latvia. Experimental Featured on August 15, 2022, Wallpapers, Textures & Patterns. Krišjānis Kazaks
  
  